### ISSUE TITLE
dev: DataFeed parsing

### ISSUE THREAD

**Issue by EvolveArt** [astraly-labs/pragma-monorepo#15]
**Goal**

Implement parsing of the data feed structure.
We should be able to easily add a new data feed structure.

**Comment by JordyRo1** [comment]
The input data will be a byte array, with the first x-bytes associated to the type of structure the array contains. To parse this encoded array, two options: 
 - One contract DataParser.sol that contains a mapping (x-bytes -> Associated structure). By deconding the x-bytes, we get the following structure, and we can process to the parsing. If we want to add more structure, this contract must be upgradeable. 
 - One contract DataParser.sol and multiple contracts Parser.sol: the DataParser contract just realize the redirection to the Parser Contract based on the x-bytes (mapping x-bytes -> Contract), by calling the `parse` contract on the wanted Parser.sol. This method requires to have as much parser as structure to be defined, but is more manageable, because we just define a `update_parser` on the DataParser.sol to add a new parser. Also safer, because no upgradeability required.

**Comment by JordyRo1** [comment]
Went with the second option. However, an issue: DataParser.sol decodes the 2 bytes of the encoded data to determine the type of data. Then it checks its mapping if this type of data is associated to a specific parser. If the parser is found, it calls the `parse` contract of the specific Parser.sol, which will be responsible of decoding the data and return the associated strcuture. The problem is the following: in DataParser.sol, we are calling the `parse` function, which will process the data as explained and call the `parse` function of the specific Parser.sol. Ideally the result structure should be passed from the Parser.sol `parse` to DataParser.sol `parse`, responsible of displaying the result. However, this won't be possible because DataParser.sol does not have the structure itself.

**Comment by JordyRo1** [comment]
I think we might have to fallback to the first option. The reason is that the `parse` function of the DataParser.sol will not be able to return a structure that is existing in the Parser.sol contract, because the return type must be known as part of the signature. The only way to transmit the information would be through `bytes memory` which defies the purpose of the parse contract.
