### ISSUE TITLE
dev: metadata struct

### ISSUE THREAD

**Issue by EvolveArt** [astraly-labs/pragma-monorepo#84]
**Current Behavior**

Right now the metadata struct is in every struct `SpotMedian`, `Twap`.

```solidity
struct Metadata {
    bytes32 feedId;
    uint64 timestamp;
    uint16 numberOfSources;
    uint8 decimals;
}

struct SpotMedian {
    Metadata metadata;
    uint256 price;
    uint256 volume;
}

struct TWAP {
    Metadata metadata;
    uint256 twapPrice;
    uint256 timePeriod;
    uint256 startPrice;
    uint256 endPrice;
    uint256 totalVolume;
    uint256 numberOfDataPoints;
}
...
```

**Expected Behavior**

```solidity
struct ParsedData {
    Metadata metadata,
    FeedType dataType;
    SpotMedian spot;
    TWAP twap;
    RealizedVolatility rv;
    Options options;
    Perp perp;
}

struct SpotMedian {
    uint256 price;
    uint256 volume;
}
```

**Comment by JordyRo1** [comment]
Working on this. 
Setting up the metadata on the parsedData will have an impact on the storage configuration. Currently, we are storing the data feeds like this: 
```solidity
    mapping(bytes32 => SpotMedian) public spotMedianFeeds;
    mapping(bytes32 => TWAP) public twapFeeds;
    mapping(bytes32 => RealizedVolatility) public rvFeeds;
    mapping(bytes32 => Options) public optionsFeeds;
    mapping(bytes32 => Perp) public perpFeeds;
 ```
 and before updating a given data feed, we consider the associated stored feed and compare if the new publish time is greater than the stored one, like this:
 ```solidity
 if (publishTime > spotMedianFeeds[feedId].metadata.timestamp) {
                spotMedianFeeds[feedId] = parsedData.spot;
                emit EventsLib.SpotMedianUpdate(feedId, publishTime, parsedData.spot);
            }
  ```
  - If we choose to remove the metadata from the feed level, we will have to stored the ParsedData instead of spotMedianFeeds/twapFeeds/rvFeeds, ..., which is fine, but will require some additional work from the user if they want to call directly the getter. 
  Instead of calling `spotMedianFeeds(bytes32)` with the feedId, they will have to call `dataFeeds` , where 
  ` mapping(bytes32 => ParsedData) public dataFeeds`, then extract the the feed they want from the parsed data. This can lead to errors on the side of the user (if they call another feed, it will not panic but return an entry full of 0. 
  
   - An alternative solution could be to define a new storage slot for `publish_time`, where for a given feedId, we store the publish time, that will be updated at the same time as the entry itself.

**Comment by EvolveArt** [comment]
> Working on this. Setting up the metadata on the parsedData will have an impact on the storage configuration. Currently, we are storing the data feeds like this:
> 
> ```solidity
>     mapping(bytes32 => SpotMedian) public spotMedianFeeds;
>     mapping(bytes32 => TWAP) public twapFeeds;
>     mapping(bytes32 => RealizedVolatility) public rvFeeds;
>     mapping(bytes32 => Options) public optionsFeeds;
>     mapping(bytes32 => Perp) public perpFeeds;
> ```
> 
> and before updating a given data feed, we consider the associated stored feed and compare if the new publish time is greater than the stored one, like this:
> 
> ```solidity
> if (publishTime > spotMedianFeeds[feedId].metadata.timestamp) {
>                spotMedianFeeds[feedId] = parsedData.spot;
>                emit EventsLib.SpotMedianUpdate(feedId, publishTime, parsedData.spot);
>            }
> ```
> 
> * If we choose to remove the metadata from the feed level, we will have to stored the ParsedData instead of spotMedianFeeds/twapFeeds/rvFeeds, ..., which is fine, but will require some additional work from the user if they want to call directly the getter.
>   Instead of calling `spotMedianFeeds(bytes32)` with the feedId, they will have to call `dataFeeds` , where
>   ` mapping(bytes32 => ParsedData) public dataFeeds`, then extract the the feed they want from the parsed data. This can lead to errors on the side of the user (if they call another feed, it will not panic but return an entry full of 0.
> * An alternative solution could be to define a new storage slot for `publish_time`, where for a given feedId, we store the publish time, that will be updated at the same time as the entry itself.

Makes sense, let's keep it as it right now and revisit in the future if it really becomes a bottleneck
